sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=zip
  - BROWSER=firefox EXT=xpi
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  api_key:
    secure: BCCzIkUFHKotFPABHqPHHyPP8O6ZTPmtt6Ja/JltfO9XBwf6pk9jRiNuRmx5AeETGE2BpojvfqW622q9lCOpgtBit6xkHQC/r2NKt35qMBIPgGCb7GUr5KK7lHNTVOviK9gsOuxcVTeYw3w+zmGLUTpjieELgn4tyz9E8DcOeHE=
  file: dist/build/uBlock.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: gorhill/uBlock
    tags: true
    all_branches: true